//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESN.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile1
    {
        public System.Guid userId { get; set; }
        public string fName { get; set; }
        public int dob { get; set; }
        public string ImageData { get; set; }
        public string ImageMimeType { get; set; }
    }
}
